### ISSUE TITLE
Update for sensor. fails

### ISSUE THREAD

**Issue by Rrapa** [peetereczek/ztm#15]
Cześć 
Od wczoraj mam powtarzający się błąd - 2020-11-16 07:55:18 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.xxxxxx fails  i leci mi tak po wszystkich utworzonych. Co może być przyczyną? 

Rafał

**Comment by peetereczek** [comment]
Czy błąd dalej występuje? Mógłbyś zwiększyć poziom logowania?

**Comment by Rrapa** [comment]
Ten błąd przestał występować
