### ISSUE TITLE
Niewygodne wyświetlanie historii

### ISSUE THREAD

**Issue by pkrolkgp** [peetereczek/ztm#2]
W nocy autobusy i tramwaje nie kursują, więc pozostaje długi czas do następnego, psuje to ogólny widok historii, bo nie widać nic sensownego.
![obraz](https://user-images.githubusercontent.com/32438012/73597366-97bede00-452b-11ea-8cc5-3d7a71c0d892.png)

**Comment by peetereczek** [comment]
Dodam warunek który to odfiltruje. Lepiej wyświetlać 0?

**Comment by pkrolkgp** [comment]
Wydaje mi się że tak by było najlepiej.

**Comment by peetereczek** [comment]
![image](https://user-images.githubusercontent.com/42431204/73617073-4f7ee900-461b-11ea-8aae-96174f59e7a1.png)

Jutro wieczorem zrobię release. Chcę jeszcze jednego buga naprawić
