### ISSUE TITLE
Odjazd w 2 kierunkach tej samej linii z jednego przystanku

### ISSUE THREAD

**Issue by KM192** [peetereczek/ztm#3]
Taki przypadek: Linia 715 odjeżdża z tego samego przystanku w 2 różne strony:
https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2020-02-02&wtp_md=5&wtp_ln=715&wtp_st=4174&wtp_pt=02&wtp_dr=B&wtp_vr=0&wtp_dy=7&wtp_lm=1

przydałoby się aby można opcjonalnie pominąć niektóre odjazdy z pewnymi adnotacjami - np. w postaci takiej konfuguracji:
  lines:
    - number: 715
      stop_id: 4173
      stop_number: "02"
      skip_annotation: w

Poza tym - super!

**Comment by peetereczek** [comment]
Pomyślę nad dodaniem kierunku jazdy autobusu. Podejrzałem ogólnie jak wygląda integracja do BKK (transport publiczny w Budapeszcie) i jest dużo fajniejsza od tej. Można by dużo zaczerpnąć z innego projektu

**Comment by KM192** [comment]
Sam kierunek może byc ciężki do wywnioskowania.
Wystarczyłaby opcja pomijania wymienionych "literek", którymi tagowane są w rozkładzie niektóre kursy. Wtedy funkcjonalność byłaby uniwersalna np. ktoś chciałby pominąć skłądy, które kończą się inaczej - np. poprzez pominięcie kursów z literką k z tego przykładu: https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2020-02-03&wtp_md=5&wtp_ln=159&wtp_st=7038&wtp_pt=04&wtp_dr=A&wtp_vr=0&wtp_lm=1&wtp_dy=1

**Comment by peetereczek** [comment]
No dobra, ale ciągle nie będzie wiadomo dokąd autobus za x min odjeżdża.

Bardzo mi się podoba rozwiązanie wtyczki do BBK, docelowo coś takiego bym chciał zrobić
https://github.com/amaximus/bkk_stop

**Comment by KM192** [comment]
To nie tak. Zmiana polegałaby na dodaniu opcji omijania w rozkładzie tych kursów, które mają wymienione tagi z adnotacjami np:
- skip_tags: w, k

Już po stronie konfiguracji byłoby zbudowanie sobie odpowiedniej logiki co to dla mnie oznacza - przy niektórych kursach będzie chodzić o pomijaniu zjazdów do zajezdni, a przy innych np, pomijanie kursów w określonym kierunku.  Do tego przydałoby się jeszcze nadawanie własnych nazw tym wpisom z liniami.

Przykłady konfiguracji w yaml:
`
lines:
- number: 715
  stop_id: 4173
  stop_number: "02"
  skip_tags: w
  name: 715 Dawidy kierunek Wilanowska
- number: 159
  stop_id: 7038
  stop_number: "04"
  skip_tags: k
  name: 159 do Blue City pełna trasa
 `

**Comment by peetereczek** [comment]
Pomijanie może jeszcze, ale to zdecydowanie odległy ficzer do implementacji.

A nazwę możesz sobie i tak zmienić na jaką chcesz

**Comment by peetereczek** [comment]
w przyszłym tygodniu pewnie zrobię kartę customową w drugim projekcie, żeby ładnie wyświetlać najbliższe odjazdy.

O pomijaniu jakiś kierunków już można by pomyśleć na poziomie karty / wyświetlania w UI

**Comment by peetereczek** [comment]
Dedykowana karta dla tego sensora będzie tutaj: https://github.com/peetereczek/ztm_stop_card

**Comment by peetereczek** [comment]
Zamykam, kierunki będą widoczne na customowej karcie:
![image](https://user-images.githubusercontent.com/42431204/73897915-e4861a00-4887-11ea-9d2c-2f6f8cf329a9.png)

Pod kątem tej karty, warto by zmienić sposób pobierania dany aby pozbyć się wąskiej perspektywy tylko jednej linii na przystanku

**Comment by KM192** [comment]
Hmm - to jest tylko połowiczne rozwiązanie.
Po pierwsze - tak jak pisałem - nie chodzi tylko o kierunki, ale o pomijanie innych czasów odjazdu z konkretnymi przypisami.
Po drugie - to rozwiązanie dotyczy konkretnej wizualizacji. Co w sytuacjach, gdy nie ma miejsca na taką kartę (tablet), ktoś ma inną wizję wizualizacji, albo gdy ktoś chce odpowiedzieć za pomocą telegram bot-a na zapytanie kiedy następny bus ?
